Glass new feature
jajecnikmarci/ProjLab pull request #78
Opened 2024-03-30 20:51 UTC by jajecnikmarci

Lásd: Item.hasToDropItem()

2024-04-01 19:26 UTC, Velkey-Jozsef commented
Jónak tűnik

2024-04-01 19:35 UTC, kilianmarcell requested changes

2024-04-01 19:35 UTC, kilianmarcell commented on src/main/java/kevesse_kokanyolo_kod/player/Student.java
> +    public void dropRandItem() {
Szerintem jó az, ha ki van írva, hogy dropRandomItem()

2024-04-01 19:35 UTC, kilianmarcell commented on src/main/java/kevesse_kokanyolo_kod/player/Student.java
> +                killImmunity.getItem().hasToDropItem(this);
Itt nem lenne egyszerűbb csak a dropRandomItem() metódust meghívni?
És akkor nem is kéne a többi osztályban a többi metódus...

2024-04-01 19:46 UTC, kilianmarcell commented on src/main/java/kevesse_kokanyolo_kod/player/Student.java
> +                killImmunity.getItem().hasToDropItem(this);
Nem akkor ejt el egy tárgyat a hallgató, amikor használni próbálja a már aktív Glass-t?

2024-04-02 10:05 UTC, jajecnikmarci commented on src/main/java/kevesse_kokanyolo_kod/player/Student.java
> +    public void dropRandItem() {
Javítottam

2024-04-02 10:45 UTC, gb999 approved these changes

2024-04-02 10:45 UTC, merged